### ISSUE TITLE
New error on start

### ISSUE THREAD

**Issue by DiseaseNO** [CmdrShepard/Skyhook#2]
The config works great now. And skyhook is starting, but i get more errors when asking for something. Error below. Is it me missing something?

>  ***
> 
>  Starting uWSGI 2.0.14 (64bit) on [Tue Dec  6 13:44:20 2016] ***
> compiled with version: 4.9.2 on 06 December 2016 09:13:14
> 
> 
> os: Linux-3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02)
> nodename: xxxxx
> machine: x86_64
> clock source: unix
> detected number of CPU cores: 4
> current working directory: /opt/skyhook/src
> detected binary path: /opt/skyhook/venv2/bin/uwsgi
> !!! no internal routing support, rebuild with pcre support !!!
> setgid() to 33
> setuid() to 33
> your processes number limit is 15310
> your memory page size is 4096 bytes
> detected max file descriptor number: 65536
> lock engine: pthread robust mutexes
> thunder lock: disabled (you can enable it with --thunder-lock)
> uwsgi socket 0 bound to UNIX address /tmp/skyhook.sock fd 8
> Python version: 3.5.2 (default, Dec  6 2016, 00:55:03)  [GCC 4.9.2]
> 
> ***
> 
>  Python threads support is disabled. You can enable it with --enable-threads ***
> Python main interpreter initialized at 0x15e92f0
> your server socket listen backlog is limited to 100 connections
> your mercy for graceful operations on workers is 60 seconds
> mapped 145536 bytes (142 KB) for 1 cores
> *** Operational MODE: single process ***
> Starting Sonarr Skyhook v1.0.0
> WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x15e92f0 pid: 26343 (default app)
> *** uWSGI is running in multiple interpreter mode ***
> spawned uWSGI master process (pid: 26343)
> spawned uWSGI worker 1 (pid: 26346, cores: 1)
> 2016-12-06 13:48:03,633 [skyhook.cache] [DEBUG] Trying to grab show from TV maze with TVDB ID: 307674
> 2016-12-06 13:48:04,291 [skyhook.tvdb] [DEBUG] Searching TVDB for ID=307674 and language "no"
> Traceback (most recent call last):
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/tvdb_api.py", line 633, in _getetsrc
>     return ElementTree.fromstring(src)
>   File "/usr/local/lib/python3.5/xml/etree/ElementTree.py", line 1333, in XML
>     parser.feed(text)
> xml.etree.ElementTree.ParseError: syntax error: line 1, column 49
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/tvdb_api.py", line 637, in _getetsrc
>     return ElementTree.fromstring(src)
>   File "/usr/local/lib/python3.5/xml/etree/ElementTree.py", line 1333, in XML
>     parser.feed(text)
> xml.etree.ElementTree.ParseError: syntax error: line 1, column 49
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
>     response = self.make_response(self.handle_exception(e))
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "./skyhook/views.py", line 70, in shows
>     cached_show = SonarrCache.get_cached_show(tvdb_id, language, True)
>   File "./skyhook/cache.py", line 261, in get_cached_show
>     search_result = handle_search(tvdb_id, search_results)[0]
>   File "./skyhook/cache.py", line 20, in handle_search
>     sonarr_format = tvdb.to_sonarr_format(result)
>   File "./skyhook/tvdb.py", line 157, in to_sonarr_format
>     show = self.tvdb[result['id']]
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/tvdb_api.py", line 948, in __getitem__
>     self._getShowData(key, self.config['language'])
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/tvdb_api.py", line 854, in _getShowData
>     self.config['url_seriesInfo'] % (sid, getShowInLanguage)
>   File "/opt/skyhook/venv2/lib/python3.5/site-packages/tvdb_api.py", line 645, in _getetsrc
>     self.config['cache_location']
> KeyError: 'cache_location'
> [pid: 26346|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 911 bytes} [Tue Dec  6 13:48:03 2016] GET /v1/tvdb/shows/en/307674 => generated 0 bytes in 1586 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
>

**Comment by DiseaseNO** [comment]
I had forgotten API key, sorry.
